services:
  web-staging:
    image: cicd-web-demo:staging
    container_name: web-staging
    ports:
      - "8081:80"

  web-production:
    image: cicd-web-demo:production
    container_name: web-production
    ports:
      - "8082:80"
